version: '3.8'

volumes:
  pg_data:

services:
  db:
    image: postgres:16-alpine
    container_name: dev_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-code_unity}
      POSTGRES_USER: ${POSTGRES_USER:-foodgram_code_unity_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-foodgram_passwcode_unity_password}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-foodgram_code_unity_user}"]
      interval: 10s
      timeout: 5s
      retries: 5